# docker-compose.yml
version: '3'

services:
  p6:
    build: ./e-commerce
    volumes:
      - ./e-commerce:/e-commerce
      - static_volume:/e-commerce/static
    expose:
      - 8000:8000
    depends_on:
      - mongo
    command: gunicorn Ecommerce.wsgi:application --bind 0.0.0.0:8000

  mongo:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - p6
    volumes:
      - static_volume:/e-commerce/static

volumes:
  static_volume:
